name: vxsacademy
description: vexcess academy
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.3.0
  json5: ^0.8.2
  mongo_dart: ^0.10.4
  path: ^1.9.1
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
