// transpiler is vibe coded
// but I've verified the output is correct

const fs = require("fs");

function transpileDartToJS(dartCode) {
    let js = dartCode;

    // 1. Handle "is!" and "is" (Type Checks)
    // We use placeholders for EVERYTHING to prevent the Step 4 "Equality War"
    js = js.replace(/([\w\[\]"' \.]+)is!\s+String/g, 'typeof $1 __STRICT_NEQ__ "string"');
    js = js.replace(/([\w\[\]"' \.]+)is!\s+num/g, 'typeof $1 __STRICT_NEQ__ "number"');
    js = js.replace(/([\w\[\]"' \.]+)is!\s+Map/g, '(typeof $1 __STRICT_NEQ__ "object" || $1 __STRICT_NEQ__ null || Array.isArray($1))');
    
    js = js.replace(/([\w\[\]"' \.]+)is(?!!)\s+String/g, 'typeof $1 __STRICT_EQ__ "string"');
    js = js.replace(/([\w\[\]"' \.]+)is(?!!)\s+num/g, 'typeof $1 __STRICT_EQ__ "number"');
    js = js.replace(/([\w\[\]"' \.]+)is(?!!)\s+Map/g, '(typeof $1 __STRICT_EQ__ "object" && $1 __STRICT_NEQ__ null && !Array.isArray($1))');

    // 2. Handle Function Declarations
    js = js.replace(/^(?!\s*(?:if|for|while|switch|return))\b(?:[\w<> ,]+)\s+(\w+)\s*\(/gm, 'function $1(');

    // 3. Smart Parameter Cleanup
    js = js.replace(/(function \w+\()([^)]+)\)/g, function(match, funcHead, params) {
        let cleaned = params.split(/,(?![^<]*>)/).map(p => {
            let parts = p.trim().split(/\s+/);
            return parts[parts.length - 1]; 
        }).join(', ');
        return funcHead + cleaned + ")";
    });

    // 4. Strict Equality Fix for normal operators (e.g., data.parent != null)
    // This only touches literal "==" or "!=" not already tripled
    js = js.replace(/==(?!=)/g, '===');
    js = js.replace(/!=(?!=)/g, '!==');

    // 5. Swap Placeholders back to Strict Operators
    js = js.replaceAll('__STRICT_EQ__', '===');
    js = js.replaceAll('__STRICT_NEQ__', '!==');

    // 6. Method & Logic translations
    js = js.replaceAll('.codeUnitAt(', '.charCodeAt(');
    js = js.replaceAll('.contains(', '.includes(');
    js = js.replaceAll('.isEmpty', '.length === 0');
    js = js.replaceAll('.containsKey(', '.hasOwnProperty(');
    js = js.replace(/(\w+)\.keys\.length/g, 'Object.keys($1).length');

    // 7. Constructor/Casting cleanup
    js = js.replace(/List<[^>]+>\.from\(([^)]+)\)/g, 'Array.from($1)');
    js = js.replace(/\s+as\s+[\w<> ,]+/g, ''); 

    // 8. Regex, Loops, and Syntax
    js = js.replace(/RegExp\(r'([^']+)'\)/g, '/$1/'); 
    js = js.replace(/\.hasMatch\((\w+)\)/g, '.test($1)'); 
    js = js.replace(/for\s*\(\s*var\s+(\w+)\s+in\s+([\w\[\]"']+)\.keys\s*\)/g, 'for (let $1 in $2)');
    
    // 9. Indentation-Safe Cleanup
    js = js.replace(/(\S) {2,}/g, '$1 ');

    return js;
}

const dart = fs.readFileSync("./backend/lib/validators.dart").toString();
const js = transpileDartToJS(dart);
console.log("// generated by transpile.js\n// no not edit\n" + js);